### ISSUE TITLE
Current status of the project?

### ISSUE THREAD

**Issue by Renha** [research-team/NEUCOGAR#41]
Hello.

We've found the project very interesting, but codebase has no updates for couple of years, not even usual code maintaining.

What the reason? Is project closed, out of sync with developer repos, or what?

**Comment by Panzerwaffe** [comment]
The project is closed

**Comment by Renha** [comment]
Thank you. Is it more like finished-closed, or abandoned-closed?

**Comment by Panzerwaffe** [comment]
Finished-closed. We have reached our goals by long-time simulations
